name: CI of FastAPI Project

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Test FastAPI app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lint (flake8 or black)
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: |
          pip install pytest pytest-asyncio httpx
          pytest -v